package cincuentazo.controller;

import cincuentazo.view.CincuentazoFinalStage;
import cincuentazo.view.CincuentazoWelcomeStage;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Label;

import java.io.IOException;

/**
 * Controller class for the final screen of the Cincuentazo application.
 * <p>
 * This controller manages user interactions on the "Final" stage,
 * such as displaying the winner and returning to the main menu after the game ends.
 */
public class CincuentazoFinalController {

    /**
     * Label displaying the winner's name.
     */
    @FXML
    private Label winnerLabel;

    /**
     * Sets the winner's name to be displayed.
     *
     * @param winner the name of the winning player.
     */
    public void setWinner(String winner) {
        winnerLabel.setText("¡Ganador: " + winner + "!");
    }

    /**
     * Handles the action of returning to the main menu.
     * <p>
     * When triggered, this method opens the {@link CincuentazoWelcomeStage}
     * and closes the current {@link CincuentazoFinalStage}.
     *
     * @param event the {@link ActionEvent} generated by the menu button click.
     */
    @FXML
    void handleMenu(ActionEvent event) {
        try {
            CincuentazoWelcomeStage.getInstance();
            CincuentazoFinalStage.deleteInstance();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}