package cincuentazo.controller;

import cincuentazo.view.CincuentazoHelpStage;
import cincuentazo.view.CincuentazoWelcomeStage;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;

import java.io.IOException;

/**
 * Controller class for the help screen of the Cincuentazo application.
 * <p>
 * This controller manages user interactions within the help window,
 * such as navigating back to the main menu.
 */
public class CincuentazoHelpController {

    /**
     * Handles the action of returning to the main menu.
     * <p>
     * When triggered, this method opens the {@link CincuentazoWelcomeStage}
     * and closes the current {@link CincuentazoHelpStage}.
     *
     * @param event the {@link ActionEvent} generated by the "Back" button click.
     */
    @FXML
    void handleBack(ActionEvent event) {
        try {
            CincuentazoWelcomeStage.getInstance();
            CincuentazoHelpStage.deleteInstance();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}